spring:
    application:
        name: taxi

    datasource:
        url: jdbc:mysql://localhost:3306/taxi?useSSL=false&serverTimezone=UTC
        username: root
        password: jorgeNieto1
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect


